Vagrant.configure("2") do |config|
  config.vm.define "VM1" do |vm|
    vm.vm.box = "bento/ubuntu-24.04"
    vm.vm.network "public_network", type: "dhcp", name: "vboxnet3" 
    vm.vm.network "forwarded_port", guest: 80, host: 8080
    vm.vm.synced_folder "./shared", "/vagrant_share"
    vm.vm.hostname = "webserver"
    vm.vm.provider "virtualbox" do |vi|
      vi.memory = 1024
      vi.cpus = 1
    end
    vm.vm.provision "shell", path: "./scriptvm1.sh"
  end
  config.vm.define "VM2" do |vm|
    vm.vm.box = "bento/ubuntu-24.04"
    vm.vm.network "public_network", type: "dhcp", name: "vboxnet3" 
    vm.vm.synced_folder "./shared", "/vagrant_share"
    vm.vm.hostname = "webserver2"
    vm.vm.provider "virtualbox" do |vi|
      vi.memory = 1024
      vi.cpus = 1
    end
    vm.vm.provision "shell", path: "./scriptvm2.sh"
  end
  config.vm.define "VM3" do |vm|
    vm.vm.box = "bento/ubuntu-24.04"
    vm.vm.network "public_network", type: "dhcp", name: "vboxnet3" 
    vm.vm.synced_folder "./shared", "/vagrant_share"
    vm.vm.hostname = "webserver3"
    vm.vm.provider "virtualbox" do |vi|
      vi.memory = 1024
      vi.cpus = 1
    end
    vm.vm.provision "shell", path: "./scriptvm3.sh"
  end
end