---
- name: Baseline configuration
  hosts: all
  roles:
    - baseline

- name: Configure Firewall
  hosts: all
  roles:
    - firewall

- name: Configure Nginx with Vault
  hosts: webservers
  become: true
  vars_files:
    - vars/secrets.yml
  roles:
    - nginx
