---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Deploy Nginx configuration
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Deploy index.html
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
